create database eispdm_sis;
create table ROL(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(100)
);
create table USUARIOS(
 ID INT PRIMARY KEY AUTO_INCREMENT,
 NOMBRES VARCHAR(200),
 AP_PATERNO VARCHAR (50),
 AP_MATERNO VARCHAR(50),
 CORREO VARCHAR(200),
 CI VARCHAR(20),
 CLAVE VARCHAR(1000),
 ESTADO BINARY,
 FECHA_REGISTRO DATETIME,
 FECHA_BAJA DATETIME,
 ID_ROL INT,   
 FOREIGN KEY(ID_ROL) REFERENCES ROL(ID)   
);


ALTER TABLE ROL ADD COLUMN DESCRIPCION VARCHAR(350);

INSERT INTO ROL(NOMBRE,DESCRIPCION) VALUES('ADMINISTRADOR','Tiene acceso a todo el sistema.');
INSERT INTO ROL(NOMBRE,DESCRIPCION) VALUES('ENCARGADO GABINETE','Encargado de realizar los inventarios de laboratorios, y de aprobar los prestamos de equipos a docentes y estudiantes.');
INSERT INTO ROL(NOMBRE,DESCRIPCION) VALUES('JEFE', 'Hace seguimiento al sistema sin realizar modificación ni solicitudes.');
INSERT INTO ROL(NOMBRE,DESCRIPCION) VALUES('DOCENTE','Realiza pedido de equipos y otros materiales para el desarrollo de práticas en laboratorios.');
INSERT INTO ROL(NOMBRE,DESCRIPCION) VALUES('ESTUDIANTE','Estudiante de la carrera con matricula vigente.');

ALTER TABLE USUARIOS ADD COLUMN FOTO VARCHAR(3000);

CREATE TABLE CATEGORIA(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(200),
DESCRIPCION VARCHAR(1000),
ESTADO BINARY);

CREATE TABLE LABORATORIO(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_LABORATORIO VARCHAR(300),
EDIFICIO VARCHAR(300),
ESTADO BINARY
);

CREATE TABLE NUMEROS_SERIES(
ID INT PRIMARY KEY AUTO_INCREMENT,
NUMERO_SERIE VARCHAR(100),
FECHA_GENERADA DATETIME,
ESTADO BINARY,
FECHA_BAJA DATETIME);

CREATE TABLE MATERIA (
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(300),
SEMESTRE VARCHAR(1),
ESTADO BINARY
);

CREATE TABLE CODIGO(
ID INT PRIMARY KEY AUTO_INCREMENT,
CODIGO VARCHAR(6),
FECHA_GENERADO DATETIME,
ESTADO BINARY);

CREATE TABLE INVENTARIO(
ID INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(350),
ID_CATEGORIA INT,
FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID),
MARCA VARCHAR(350),
MODELO VARCHAR(350),
DESCRIPCION VARCHAR(1000),
CANTIDAD INT,
SERIAL VARCHAR(100),
FECHA_INGRESO DATETIME,
FECHA_BAJA DATETIME,
ESTADO BINARY,
CONDICION VARCHAR(20),
ID_USUARIO_REGISTRO INT,
FOREIGN KEY(USUARIO_REGISTRO) REFERENCES USUARIOS(ID),    
ID_USUARIO_BAJA INT,
FOREIGN KEY(ID_USUARIO_BAJA) REFERENCES USUARIOS(ID), 
FOTO VARCHAR(3000)   
);

CREATE TABLE  PRESTAMO(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_CODIGO INT,
FOREIGN KEY(ID_CODIGO) REFERENCES CODIGO(ID),
ESTADO BINARY,
ID_MATERIA INT,
FOREIGN KEY(ID_MATERIA) REFERENCES MATERIA(ID), 
ID_LABORATORIO INT,
FOREIGN KEY(ID_LABORATORIO) REFERENCES LABORATORIO(ID),   
FECHA_ENTREGA DATETIME,
FECHA_PEDIDO DATETIME,
FECHA_DEVUELTO DATETIME,
FECHA_CAMBIO DATETIME,
ID_DOCENTE INT,
FOREIGN KEY(ID_DOCENTE) REFERENCES USUARIOS(ID),     
ID_GABINETE INT,
FOREIGN KEY(ID_GABINETE) REFERENCES USUARIOS(ID),     
CORREO_ESTUDIANTE VARCHAR(200)
);

CREATE TABLE PRESTAMODETALLE(
ID INT PRIMARY KEY AUTO_INCREMENT,
ID_PRESTAMO INT,
FOREIGN KEY(ID_PRESTAMO) REFERENCES PRESTAMO(ID),    
ID_INVENTARIO INT,
FOREIGN KEY(ID_INVENTARIO) REFERENCES INVENTARIO(ID),       
ESTADO BINARY    
);